export default {
    ac: 15,
    actions: [],
    alignment: "Neutral",
    challenge: "1/8",
    conditionImmunities: [],
    damageImmunities: [],
    damageResistances: [],
    damageWeaknesses: [],
    description: "",
    features: [],
    hp: 5,
    inventory: ["500gp", "1 Key to brewing cellar"],
    languages: ["Common", "Elvish"],
    reactions: [],
    savingThrows: [],
    senses: ["Darkvision 30ft."],
    size: "Medium",
    skills: [],
    speed: "30 ft.",
    stats: {
        str: 8,
        dex: 15,
        con: 10,
        int: 12,
        wis: 12,
        cha: 10
    },
    type: "Wood Elf"
};
